flashcards = { " What is the capital of France?": "Paris",
               " What is the largest planet in our solar system?": "Jupiter",
               " What is the chemical symbol for gold?": "Au",
               " What is the square root of 64?": "8",
               " Who painted the Mona Lisa?": "Leonardo da Vinci",
               " What is the smallest prime number?": "2",
               " What is the largest mammal?": "Blue Whale",
                " What is the chemical symbol for water?": "H2O",
                " What is the capital of Japan?": "Tokyo", 
                " What is the largest ocean on Earth?": "Pacific Ocean",
                " Who is the founder of Microsoft?": "Bill Gates",
                " What is the chemical symbol for oxygen?": "O",
                " What is the largest desert in the world?": "Sahara Desert",
                " Who is the CEO of Tesla?": "Elon Musk",
                " What is the chemical symbol for carbon?": "C",
}